import java.util.List;
import java.util.ArrayList;

class EdgeTest {

	public static void main(String[] args) {
		// Edges generated by GreedyTSP 5 100000
		List<Edge> l = new ArrayList<Edge>();
		l.add(new Edge(1, 0, 2.24));
		l.add(new Edge(2, 0, 2.24));
		l.add(new Edge(2, 1, 4.0));
		l.add(new Edge(3, 0, 2.24));
		l.add(new Edge(3, 1, 3.16));
		l.add(new Edge(3, 2, 1.41));
		l.add(new Edge(4, 0, 1.41));
		l.add(new Edge(4, 1, 2.24));
		l.add(new Edge(4, 2, 3.61));
		l.add(new Edge(4, 3, 3.61));
		l = Quicksort.quicksort(l);
		for (Edge e : l) {
			System.out.printf("%f %d %d\n", e.weight, e.row, e.column);
		}
	}


}